#!/bin/bash

# `./run st` fixes lint and displays the current status of the codebase.

fix >/dev/null 2>&1

git add .
PAGER= git diff --cached

if typecheck >/dev/null 2>&1; then
    echo "types: pass"
else
    echo "types: FAIL"
fi

if test.ts >/dev/null 2>&1; then
    echo "tests: pass"
else
    echo "tests: FAIL"
fi

if lint >/dev/null 2>&1; then
    echo "lint:  pass"
else
    echo "lint:  FAIL"
fi
